<form method="post" action="index.php">
    <fieldset>
        <label for="firstName">First Name:</label>
        <input type="text" id="firstName" name="firstName">
    </fieldset>
    <fieldset>
        <label for="lastName">Last Name:</label>
        <input type="text" id="lastName" name="lastName">
    </fieldset>
    <fieldset>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email">
    </fieldset>
    <fieldset>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
    </fieldset>
    <fieldset>
        <label for="confirmPassword">Confirm Password:</label>
        <input type="password" id="confirmPassword" name="confirmPassword">
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" value="formName">
    </fieldset>
    <fieldset>
        <input type="submit" value="Créer mon compte">
    </fieldset>
</form>

