<form method="post" action="index.php">
    <fieldset>
        <label for="loginEmail">Email:</label>
        <input type="email" id="loginEmail" name="loginEmail">
    </fieldset>
    <fieldset>
        <label for="loginPassword">Password:</label>
        <input type="password" id="loginPassword" name="loginPassword">
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" value="formName">
    </fieldset>
    <fieldset>
        <input type="submit" value="Se connecter">
    </fieldset>
</form> 
