<!DOCTYPE html>
<html>
    <head>
        
    </head>
    <body>
        
        <!-- HEADER -->
        
        <?php require "partials/_header.phtml"; ?>
        
        <!-- MAIN -->
        
        <?php   
            
            require $template."/".$template.".phtml";
                
        ?>
        
        <!-- FOOTER -->
        
        <?php require "partials/_footer.phtml"; ?>
        
    </body>
</html>