<form>
    <fieldset>
        <label for="title">Titre:</label>
        <input type="text" name="title" id="title">
    </fieldset>
    <fieldset>
        <label for="content">Contenu:</label>
        <input type="text" name="content" id="content">
    </fieldset>
    <fieldset>
        <label for="author">Auteur:</label>
        <input type="text" name="author" id="author">
    </fieldset>
    <fieldset>
        <label for="category">Choisir la catégorie:</label>
        <input type="text" name="category" id="category">  
    </fieldset>
</form>